### ISSUE TITLE
Timer as IGT

### ISSUE THREAD

**Issue by GameHackFan** [Wins1ey/LAST#13]
Hi, does LAST support IGT, I am porting Dino Crisis Live Splits to LAST, it works fine apparently but it uses RTA instead of IGT, is there any way to make it work with IGT?

**Comment by Loomeh** [comment]
> I had a look at some examples, I ported RE Any% and it work perfectly and I ported Dino Crisis, both a made minor changes but I don't know how to make the splitter work as IGT instead of RTA. Is there any function that allows the auto splitter to change the timer?

I'm not sure what you mean. LAST will automatically switch to IGT if an autosplitter is loaded. If it doesn't then it means that there's an error with your autosplitter. Would you mind posting a link to it?
