### ISSUE TITLE
Hardcoded sudo in Makefile makes installing in systems without sudo impossible

### ISSUE THREAD

**Issue by Aicaya** [wins1ey/LAST#15]
Pretty much what the title says. I use a system that has doas instead of sudo installed and I had to delete every single usage of sudo in order for it to compile.

Why does the Makefile have sudo in every install/uninstall command?  Usually Makefiles expect the user to add sudo or doas to `make` for those tasks, so this is kind of strange to encounter. There's other weirdness in the Makefile that doesn't make sense (such as not using PREFIX to make sure everything goes into `/usr/local` and instead dropping everything in `/usr` *except* the bin), but this is the only one that actively prevents compilation.

**Comment by Loomeh** [comment]
> Pretty much what the title says. I use a system that has doas instead of sudo installed and I had to delete every single usage of sudo in order for it to compile.
> 
> Why does the Makefile have sudo in every install/uninstall command?  Usually Makefiles expect the user to add sudo or doas to `make` for those tasks, so this is kind of strange to encounter. There's other weirdness in the Makefile that doesn't make sense (such as not using PREFIX to make sure everything goes into `/usr/local` and instead dropping everything in `/usr` *except* the bin), but this is the only one that actively prevents compilation.

It's been a while since I worked on this, but I think the reasoning for that was because if you didn't run as sudo, GDK would complain on some distros. I'm starting to address Makefile concerns on my local fork of LAST.

**Comment by Aicaya** [comment]
> [...] I think the reasoning for that was because if you didn't run as sudo, GDK would complain on some distros.

Fair enough. I also noticed just now that the branch here with your name on it has a Makefile without sudo in it, so I probably should've checked branches other than main before submitting an issue.
